### ISSUE TITLE
Implement Shadow Dash Prototype

### ISSUE THREAD

**Issue by alynch14** [alynch14/Foxhole#16]
*Description*

We want fox to dash. As per past discussions, we want to implement some type of "shadow" dash. While we do not have the animation for this ability, we can at least develop a prototype to look at how it affects the design of the game world and fits in to our game.

The dash prototype should allow for the various forces applied to the fox (player object) to be updated in the editor for ease of testing. Inpiration for this was gained through the dashing function in Hollow Knight.

*Completion Criteria*

* Fox object has the ability to dash along the ground and air
* As stated above, forces applied to fox object via the dash script should be modifiable from within the inspector for the project
* Demo to team when complete

**Comment by Bookfan97** [comment]
[Branch](/alynch14/Foxhole/tree/Shadow-Dash): Shadow-Dash
[Commit](alynch14/Foxhole/commit/5c735a53d549aa563ecd0eba23c88466a9e5d77c)
