### ISSUE TITLE
Research Testing Frameworks for Unity Projects

### ISSUE THREAD

**Issue by alynch14** [alynch14/Foxhole#20]
**Description**

We want to create tests to make sure that we do not break our game as we make changes to the source code. These include unit, integration, and possible UI tests. We need to do research into what is out there to find what will work best for us as a team.

**Completion Criteria**

* Research is documented on potential testing frameworks in the project's wiki
* README is updated to show which framework is ultimately chosen

**Comment by Bookfan97** [comment]
https://github.com/alynch14/Foxhole/wiki/Unit-Testing

**Comment by Bookfan97** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unit Testing](https://trello.com/c/SgjKFczB/21-unit-testing)

**Comment by Bookfan97** [comment]
Starting documentation: [https://github.com/alynch14/Foxhole/wiki/Unit-Testing-(Investigation)](https://github.com/alynch14/Foxhole/wiki/Unit-Testing-(Investigation))

**Comment by Bookfan97** [comment]
After some research, how the code is currently written seems to make some of the unit tests harder to write. Most unit testing resources suggest using a [humble object pattern](https://unity3d.college/2018/11/07/humble-object-game-programming-patterns-unity-c-makes-unit-testing-easy/) to make writing and developing unit tests easier. This would require some slight refactoring to the code, but nothing major. Unity also has some built-in testing functionality for the new input system that may be worth looking into (currently, the project is using the legacy input manager. If we are looking to develop for platforms beyond Mac/PC, this may be an easier option handle input).
