### ISSUE TITLE
Implement Basic Game Controller to test player/bat interactions

### ISSUE THREAD

**Issue by alynch14** [alynch14/Foxhole#26]
**Summary**

We need a game controller that will control player interactions with the rest of the enemies, npcs, and general game world. For now, we want it to aggro bats on the player when a bat's sonar collides with the player object. This task will be to implement the general game controller along with making the bats aggro on the player on sonar collision.

**Completion Criteria**

1. Extendable game controller is created
2. Bat gets aggroed when its sonar collides with the player

**Comment by Bookfan97** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [t](https://trello.com/c/UVI5hUGd/1-t)
